version: 2.1

orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@2.2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages: 
          pkg-manager: npm
      - run : 
          name : Run build
          command: npm run build 
#       - run:
#           name: Run tests
#           command: npm test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - cypress/run:
          start: npm start
      - build

# VS Code Extension Version: 1.3.0
